name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ${{ matrix.os[0] }}
    strategy:
      matrix:
        os: [
          [macos-latest, arm64, bash],
          [macos-13, x86_64, bash],
          [ubuntu-latest, x86_64, bash],
        ]
      fail-fast: false
    defaults:
     run:
      shell: ${{ matrix.os[2] }} {0}

    steps:
    - uses: actions/checkout@v4
    
    - name : Install dependencies on required OS
      run: | 
        ./prepare.sh

    - name : Build Project
      run: | 
        ./build_daedalus.sh
    - name: Prepare artifacts
      run: |
        tar -zcvf DaedalusX64-${{matrix.os[0]}}-${{matrix.os[1]}}.tar.gz \
          DaedalusX64/daedalus \
          DaedalusX64/n64.psh \
          DaedalusX64/roms.ini \
          DaedalusX64/readme.txt \
          DaedalusX64/copying.txt \
          DaedalusX64/Resources \
          DaedalusX64/Languages \
          DaedalusX64/ControllerConfigs \

    - uses: actions/upload-artifact@v4
      with:
        name: DaedalusX64-${{matrix.os[0]}}-${{matrix.os[1]}}
        path: DaedalusX64-${{matrix.os[0]}}-${{matrix.os[1]}}.tar.gz

    - name: Create pre-release
      if: ${{ github.ref == 'refs/heads/master' }}
      uses: softprops/action-gh-release@v2
      with: 
        files: DaedalusX64-${{matrix.os[0]}}-${{matrix.os[1]}}.tar.gz
        prerelease: true
        tag_name: latest"
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Release
      if: ${{ github.ref_type == 'tag' }}
      uses: softprops/action-gh-release@v2
      with:
        files: DaedalusX64-${{matrix.os[0]}}-${{matrix.os[1]}}.tar.gz
        tag_name: latest"
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-psp:
    runs-on: ubuntu-latest
    container: 'pspdev/pspdev:latest'
    env: 
      BUILD: PSP
    steps:
      - uses: actions/checkout@v4
      - name: PSP Build
        run:  ./build_daedalus.sh PSP
  

  build-ctr:
    runs-on: ubuntu-latest
    container: 'devkitpro/devkitarm:latest'
    env:
      BUILD: CTR
    steps:
      - uses: actions/checkout@v4
      - name: Prepare OS
        run: ./prepare.sh

      - name: CTR Build
        run:  ./build_daedalus.sh CTR

